version: "2"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80" # change the left port to satisfy your local env
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./docker/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    links:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33061:3306" # change the left port to satisfy your local env
    environment:
      - "MYSQL_DATABASE=autocomplete"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=pass"
      - "MYSQL_ROOT_PASSWORD=pass"
    volumes:
      - autocomplete-data:/var/lib/mysql

volumes:
  autocomplete-data:
